site_name: Limulator

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            #show_source: false
            show_root_heading: false
      watch:
        - main2.py
        - server_processing.py
        - Modules/laser.py
        - Modules/camera.py
        - Modules/global_data.py
        - Modules/limulator_platform.py
        - Modules/logger.py
        - Modules/multiprocess_script.py
  - autorefs 
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocs-video

theme:
    #name: readthedocs
    name: "material"
    features:
      - navigation.tabs
      - navigation.instant
      - navigation.tabs.sticky
      #- navigation.sections
      - navigation.expand
      - navigation.tracking
      #- header.autohide
extra:
  version:
    default: stable
  generator: false

copyright: Copyright &copy; 2022 Team Limulator